/**
 * build-real2-plates.mts — turn a saved production teaser scan into the
 * v28-v30 ad plates. Every byte is real:
 *
 *   aerial    — the scan's own Google tile (900×580 canvas geometry)
 *   parcel    — the county boundary ring, canvas px, straight from the
 *               scan's suggested runs (ReportAll via the live app)
 *   pxPerFt   — derived from the ring's shoelace area vs the recorded
 *               parcel acreage (no key needed, exact to the rounding)
 *   elevation — USGS 3DEP (epqs.nationalmap.gov) sampled on the same
 *               18×12 lattice the estimator uses; georeferenced by the
 *               scan's center = parcel centroid ≙ canvas (450,290)
 *
 * usage: npx tsx src/build-real2-plates.mts /tmp/teaser-<addr>.json
 * writes: plates/real2-aerial.png, real2-parcel.js, real2-topo.js,
 *         real2-meta.json
 */
import { readFileSync, writeFileSync } from "fs";
import { buildContours, pickContourInterval } from "@/lib/fence/contours";
import { resolveMarket } from "@/lib/fence/market";

const CANVAS_W = 900, CANVAS_H = 580;
const SRC = process.argv[2] || "/tmp/teaser-230aveB.json";
const DIR = new URL("./plates/", import.meta.url).pathname;
const rnd = (n: number) => Math.round(n * 10) / 10;

const t = JSON.parse(readFileSync(SRC, "utf8")).teaser;
const ring: [number, number][] = t.runs[0].points.map((p: { x: number; y: number }) => [p.x, p.y]);

/* ---------- aerial ---------- */
const b64 = t.image.dataUrl.split(",")[1];
writeFileSync(`${DIR}real2-aerial.png`, Buffer.from(b64, "base64"));
console.log("aerial → real2-aerial.png", t.image.width, "x", t.image.height);

/* ---------- scale: shoelace px² vs recorded acres ---------- */
let area2 = 0;
for (let i = 0; i < ring.length - 1; i++)
  area2 += ring[i][0] * ring[i + 1][1] - ring[i + 1][0] * ring[i][1];
const areaPx = Math.abs(area2) / 2;
const areaFt = t.acres * 43560;
const pxPerFt = Math.sqrt(areaPx / areaFt);
console.log(`scale: ${areaPx.toFixed(0)} px² / ${areaFt.toFixed(0)} ft² → ${pxPerFt.toFixed(4)} px/ft`);

/* ---------- geocode the anchor via the US Census (free, real) ------- */
const cu = new URL("https://geocoding.geo.census.gov/geocoder/locations/onelineaddress");
cu.searchParams.set("address", t.address.replace(/, USA$/, ""));
cu.searchParams.set("benchmark", "Public_AR_Current");
cu.searchParams.set("format", "json");
const cg = await (await fetch(cu)).json();
const match = cg?.result?.addressMatches?.[0];
if (!match) throw new Error("census geocoder: no match");
const anchor = { lat: match.coordinates.y as number, lng: match.coordinates.x as number };
console.log("census anchor:", JSON.stringify(anchor));

/* canvas (450,290) = parcel centroid = scan center; ft offsets → lat/lng */
const FT2M = 0.3048;
const mPerPx = FT2M / pxPerFt;
const latLngAt = (x: number, y: number) => {
  const dxM = (x - 450) * mPerPx;
  const dyM = (y - 290) * mPerPx; // canvas y grows south
  const lat = anchor.lat - dyM / 111320;
  const lng = anchor.lng + dxM / (111320 * Math.cos((anchor.lat * Math.PI) / 180));
  return { lat, lng };
};

/* ---------- USGS 3DEP elevation, estimator lattice ---------- */
const COLS = 18, ROWS = 12;
const jobs: { r: number; c: number; lat: number; lng: number }[] = [];
for (let r = 0; r < ROWS; r++)
  for (let c = 0; c < COLS; c++) {
    const p = latLngAt((c * CANVAS_W) / (COLS - 1), (r * CANVAS_H) / (ROWS - 1));
    jobs.push({ r, c, ...p });
  }
const grid: number[][] = Array.from({ length: ROWS }, () => Array(COLS).fill(0));
let done = 0;
async function fetchOne(j: (typeof jobs)[number], attempt = 0): Promise<void> {
  const u = new URL("https://epqs.nationalmap.gov/v1/json");
  u.searchParams.set("x", String(j.lng));
  u.searchParams.set("y", String(j.lat));
  u.searchParams.set("units", "Feet");
  u.searchParams.set("wkid", "4326");
  try {
    const res = await (await fetch(u, { signal: AbortSignal.timeout(15000) })).json();
    const v = Number(res.value);
    if (!Number.isFinite(v)) throw new Error("bad value");
    grid[j.r][j.c] = v;
    if (++done % 36 === 0) console.log(`  elevation ${done}/216`);
  } catch (e) {
    if (attempt < 3) return fetchOne(j, attempt + 1);
    throw new Error(`epqs failed at r${j.r}c${j.c}: ${e}`);
  }
}
const CONC = 8;
for (let i = 0; i < jobs.length; i += CONC)
  await Promise.all(jobs.slice(i, i + CONC).map((j) => fetchOne(j)));

let min = Infinity, max = -Infinity;
for (const row of grid) for (const v of row) { min = Math.min(min, v); max = Math.max(max, v); }
const intervalFt = pickContourInterval(min, max);
const rel = grid.map((row) => row.map((v) => v - min));
const lines = buildContours(rel, CANVAS_W / (COLS - 1), CANVAS_H / (ROWS - 1), intervalFt);
writeFileSync(
  `${DIR}real2-topo.js`,
  `/* generated by build-real2-plates.mts — USGS 3DEP */\nwindow.REAL2_TOPO = ${JSON.stringify({
    intervalFt,
    riseFt: rnd(max - min),
    lines: lines.map((l) => ({ levelFt: rnd(l.levelFt), chains: l.chains.map((ch) => ch.map((p) => [rnd(p.x), rnd(p.y)])) })),
  })};\nwindow.REAL2_GRID = ${JSON.stringify(rel.map((row) => row.map(rnd)))};\n`,
);
console.log(`elevation: span ${(max - min).toFixed(1)} ft · interval ${intervalFt}′ · ${lines.length} levels`);

/* ---------- parcel + meta ---------- */
writeFileSync(
  `${DIR}real2-parcel.js`,
  `/* generated — county parcel ring via the live scan */\nwindow.REAL2_PARCEL = ${JSON.stringify({
    ring: ring.map(([x, y]) => [rnd(x), rnd(y)]),
    acres: t.acres,
    sides: t.sides,
    corners: t.corners,
  })};\n`,
);
const market = resolveMarket({ address: t.address });
writeFileSync(
  `${DIR}real2-meta.json`,
  JSON.stringify({ address: t.address.replace(/, USA$/, ""), pxPerFt: rnd(pxPerFt * 1000) / 1000, acres: t.acres, anchor, market: { label: market.label, labor: market.labor } }, null, 2),
);
console.log("plates complete");
process.exit(0);
