/**
 * compute-real-job.mts — price the Snohomish enclosure with the real engine.
 *
 * The fence: a backyard/meadow enclosure tied into the house on both
 * sides (NOT the 5-acre boundary) — down the west tree line, across the
 * top of the clearing, back along the east side. One 4′ walk gate on
 * the west tie-in, one 10′ drive gate on the top run where the trail
 * leaves the clearing.
 *
 * Everything downstream is computed, not typed: footage from the drawn
 * polygon at the scan's real px/ft, slope from the real elevation
 * lattice sampled at post positions, terrain + steps + tier prices from
 * the shipping takeoff/pricing engine with the real Washington market.
 *
 * writes: src/plates/real-job.js
 */
import { readFileSync, writeFileSync } from "fs";
import { canvasPolylineFt, countCornersAndEnds, walkPostPositions } from "@/lib/fence/geo";
import { summarizeSlopes } from "@/lib/fence/slope";
import { computeFenceTakeoff } from "@/lib/fence/takeoff";
import { fenceTiers, priceFence } from "@/lib/fence/pricing";
import { fenceType } from "@/lib/fence/catalog";
import { resolveMarket } from "@/lib/fence/market";

const DIR = new URL("./plates/", import.meta.url).pathname;
const meta = JSON.parse(readFileSync(DIR + "real-meta.json", "utf8"));
const topoSrc = readFileSync(DIR + "real-topo.js", "utf8");
const grid: number[][] = JSON.parse(topoSrc.match(/REAL_GRID = (\[\[.*?\]\]);/s)![1]);

const PX_PER_FT = meta.pxPerFt as number;

/* the enclosure, canvas px (900×580) — house wall to house wall */
const RUN: [number, number][] = [
  [352, 415], // ties into the house's west wall
  [262, 402],
  [246, 148], // up the west tree line
  [640, 118], // across the top of the clearing
  [692, 336],
  [592, 398], // ties into the house's east wall
];
const GATES = [
  { x: 300, y: 408, kind: "single", widthFt: 4, label: "4′ walk gate" },
  { x: 528, y: 121, kind: "double", widthFt: 10, label: "10′ drive gate" },
];

const pts = RUN.map(([x, y]) => ({ x, y }));
const totalLf = Math.round(canvasPolylineFt(pts, PX_PER_FT) * 10) / 10;
const { corners, ends } = countCornersAndEnds([{ points: pts }]);

/* real elevation at every post position: bilinear over the 18×12 grid */
const COLS = 18, ROWS = 12;
const zAt = (x: number, y: number) => {
  const gx = Math.min(COLS - 1.001, Math.max(0, (x / 900) * (COLS - 1)));
  const gy = Math.min(ROWS - 1.001, Math.max(0, (y / 580) * (ROWS - 1)));
  const c0 = Math.floor(gx), r0 = Math.floor(gy);
  const fx = gx - c0, fy = gy - r0;
  return (
    grid[r0][c0] * (1 - fx) * (1 - fy) +
    grid[r0][c0 + 1] * fx * (1 - fy) +
    grid[r0 + 1][c0] * (1 - fx) * fy +
    grid[r0 + 1][c0 + 1] * fx * fy
  );
};
const spacingFt = fenceType("cedar-privacy").postSpacingFt; // 8
const posts = walkPostPositions(pts, spacingFt * PX_PER_FT);
const elev = posts.map((p) => zAt(p.x, p.y));
const slope = summarizeSlopes([elev], spacingFt, 6, "stick");

const market = resolveMarket({ address: meta.address });
const layout = {
  type: "cedar-privacy" as const,
  heightFt: 6,
  totalLf,
  runLengths: [totalLf],
  corners,
  ends,
  gatesSingle: 1,
  gatesDouble: 1,
  terrain: slope.suggestedTerrain,
  steppedSections: slope.steppedSections,
  wastePct: 10,
  market,
};

const takeoff = computeFenceTakeoff(layout as any);
const tiers = fenceTiers("cedar-privacy").map((t) => {
  const p = priceFence({ ...layout, type: t.type, stain: t.stain } as any, { markupPct: t.markupPct });
  return { name: t.name, recommended: !!t.recommended, spec: fenceType(t.type).label,
    total: Math.round(p.total), perLf: Math.round(p.pricePerLf) };
});
const chosen = tiers.find((t) => t.recommended) ?? tiers[1];

const bomq = (re: RegExp) => takeoff.bom.find((b) => re.test(b.label))?.qty ?? 0;
const job = {
  address: "12103 202nd St SE, Snohomish, WA",
  run: RUN,
  gates: GATES,
  pxPerFt: PX_PER_FT,
  totalLf,
  netLf: takeoff.netFenceLf,
  corners,
  ends,
  posts: takeoff.posts.total,
  bags: bomq(/concrete/i),
  pickets: bomq(/picket/i),
  rails: bomq(/^rails/i),
  stepRow: bomq(/step/i),
  laborHours: Math.round(takeoff.laborHours),
  slope: {
    avg: slope.avgGradePct, max: slope.maxGradePct,
    steps: slope.steppedSections, terrain: slope.suggestedTerrain,
    basePost: slope.basePostLengthFt, stepPost: slope.stepPostLengthFt,
    riseFt: Math.round((Math.max(...elev) - Math.min(...elev)) * 10) / 10,
  },
  market: { label: market.label, labor: market.labor, cedar: market.material.cedar },
  tiers,
  deposit: Math.round(chosen.total * 0.3),
  postElev: posts.map((p, i) => [Math.round(p.x * 10) / 10, Math.round(p.y * 10) / 10,
    Math.round((elev[i] - Math.min(...elev)) * 10) / 10]),
};

writeFileSync(DIR + "real-job.js", `/* generated by compute-real-job.mts */\nwindow.JOB = ${JSON.stringify(job)};\n`);
console.log(`LF ${totalLf} · net ${takeoff.netFenceLf} · corners ${corners} · posts ${takeoff.posts.total} · ${takeoff.laborHours.toFixed(0)} hrs`);
console.log(`slope: ${slope.avgGradePct}% avg · ${slope.maxGradePct}% max · ${slope.steppedSections} steps · terrain=${slope.suggestedTerrain} · rise ${job.slope.riseFt} ft · posts ${slope.basePostLengthFt}'/${slope.stepPostLengthFt}'`);
console.log("tiers:", tiers.map((t) => `${t.name}=$${t.total.toLocaleString()} ($${t.perLf}/LF)`).join(" · "));
console.log(`deposit (30%): $${job.deposit.toLocaleString()} · market ${market.label} labor×${market.labor}`);
