/**
 * fetch-real.mts — pull the REAL property for the Snohomish ad set.
 *
 * Replicates scan-core's pipeline standalone (geocode → Google Static
 * Maps satellite tile at the canvas geometry → 18×12 elevation lattice
 * like the estimator samples) so the ads run on the actual aerial and
 * the actual terrain of 12103 202nd Dr SE, Snohomish, WA — with the
 * same key the app uses.
 *
 * usage: npx tsx marketing/fence-ads/src/fetch-real.mts [zoom]
 * writes: src/plates/real-aerial-z<zoom>.png, src/plates/real-topo.js,
 *         src/plates/real-meta.json
 */
import { readFileSync, writeFileSync } from "fs";
import {
  CANVAS_W,
  CANVAS_H,
  MAP_W,
  MAP_H,
  MAP_SCALE,
  canvasPxPerFt,
  canvasToLatLng,
} from "@/lib/fence/geo";
import { buildContours, pickContourInterval } from "@/lib/fence/contours";
import { resolveMarket } from "@/lib/fence/market";

const ADDRESS = process.env.AD_ADDR || "12103 202nd Dr SE, Snohomish, WA 98296";
const ZOOM = Number(process.argv[2] || 19);

const env = readFileSync(new URL("../../../.env", import.meta.url), "utf8");
const KEY = env.match(/^GOOGLE_MAPS_API_KEY=(.+)$/m)?.[1]?.trim();
if (!KEY) throw new Error("no GOOGLE_MAPS_API_KEY in .env");

const DIR = new URL("./plates/", import.meta.url).pathname;

/* ---------- 1. geocode ---------- */
const gu = new URL("https://maps.googleapis.com/maps/api/geocode/json");
gu.searchParams.set("address", ADDRESS);
gu.searchParams.set("key", KEY);
const geo = await (await fetch(gu)).json();
if (geo.status !== "OK") throw new Error("geocode: " + geo.status);
const r0 = geo.results[0];
const loc = r0.geometry.location as { lat: number; lng: number };
const formatted = r0.formatted_address as string;
console.log("geocoded:", formatted, JSON.stringify(loc));

/* ---------- 2. satellite tile, exactly the app's geometry ---------- */
const su = new URL("https://maps.googleapis.com/maps/api/staticmap");
su.searchParams.set("center", `${loc.lat},${loc.lng}`);
su.searchParams.set("zoom", String(ZOOM));
su.searchParams.set("size", `${MAP_W}x${MAP_H}`);
su.searchParams.set("scale", String(MAP_SCALE));
su.searchParams.set("maptype", "satellite");
su.searchParams.set("key", KEY);
const img = await fetch(su);
if (!img.ok) throw new Error("staticmap: " + img.status);
const buf = Buffer.from(await img.arrayBuffer());
writeFileSync(`${DIR}real-aerial-z${ZOOM}.png`, buf);
console.log(`aerial z${ZOOM}: ${(buf.length / 1024).toFixed(0)} KB → real-aerial-z${ZOOM}.png`);

/* ---------- 3. the estimator's 18×12 elevation lattice ---------- */
const COLS = 18, ROWS = 12;
const pts: { lat: number; lng: number }[] = [];
for (let r = 0; r < ROWS; r++)
  for (let c = 0; c < COLS; c++)
    pts.push(
      canvasToLatLng(
        { x: (c * CANVAS_W) / (COLS - 1), y: (r * CANVAS_H) / (ROWS - 1) },
        loc,
        ZOOM,
      ),
    );
const eu = new URL("https://maps.googleapis.com/maps/api/elevation/json");
eu.searchParams.set("locations", pts.map((p) => `${p.lat.toFixed(7)},${p.lng.toFixed(7)}`).join("|"));
eu.searchParams.set("key", KEY);
const ele = await (await fetch(eu)).json();
if (ele.status !== "OK") throw new Error("elevation: " + ele.status);
const M2FT = 3.28084;
const flat: number[] = ele.results.map((x: any) => x.elevation * M2FT);
const grid: number[][] = [];
for (let r = 0; r < ROWS; r++) grid.push(flat.slice(r * COLS, (r + 1) * COLS));

let min = Infinity, max = -Infinity;
for (const row of grid) for (const v of row) { min = Math.min(min, v); max = Math.max(max, v); }
const intervalFt = pickContourInterval(min, max);
const rel = grid.map((row) => row.map((v) => v - min));
const lines = buildContours(rel, CANVAS_W / (COLS - 1), CANVAS_H / (ROWS - 1), intervalFt);
console.log(`elevation: span ${(max - min).toFixed(1)} ft · interval ${intervalFt}′ · ${lines.length} contour levels`);

const chainLen = (ch: { x: number; y: number }[]) => {
  let d = 0;
  for (let i = 1; i < ch.length; i++) d += Math.hypot(ch[i].x - ch[i - 1].x, ch[i].y - ch[i - 1].y);
  return d;
};
const round = (n: number) => Math.round(n * 10) / 10;
const out = lines.map((l) => {
  const chains = l.chains.map((ch) => ch.map((p) => [round(p.x), round(p.y)]));
  const labels: [number, number][] = [];
  [...l.chains].sort((a, b) => chainLen(b) - chainLen(a)).slice(0, 3).forEach((ch) => {
    if (chainLen(ch) < 70) return;
    const m = ch[Math.floor(ch.length / 2)];
    if (m.x < 26 || m.x > CANVAS_W - 26 || m.y < 26 || m.y > CANVAS_H - 26) return;
    labels.push([round(m.x), round(m.y)]);
  });
  return { levelFt: round(l.levelFt), chains, labels };
});
writeFileSync(
  `${DIR}real-topo.js`,
  `/* generated by fetch-real.mts — real Google Elevation data */\n` +
    `window.REAL_TOPO = ${JSON.stringify({ intervalFt, riseFt: round(max - min), lines: out })};\n` +
    `window.REAL_GRID = ${JSON.stringify(grid.map((r) => r.map(round)))};\n`,
);

/* ---------- 4. market + meta ---------- */
const market = resolveMarket({ address: formatted });
const meta = {
  address: formatted,
  loc,
  zoom: ZOOM,
  pxPerFt: canvasPxPerFt(loc.lat, ZOOM),
  elevSpanFt: round(max - min),
  intervalFt,
  market: { label: market.label, resolution: market.resolution, labor: market.labor,
    cedar: market.material.cedar, tax: market.salesTaxRate, basis: market.basis },
};
writeFileSync(`${DIR}real-meta.json`, JSON.stringify(meta, null, 2));
console.log("pxPerFt:", meta.pxPerFt.toFixed(3), "| market:", market.label, `(${market.resolution})`, "labor×" + market.labor);
market.basis.forEach((b) => console.log("  ·", b));
