/**
 * fetch-real2.mts — pull a real IN-TOWN lot for the boundary-line ad set
 * (v28-v30): geocode → REAL ReportAll parcel ring (the app's own client,
 * vault key) → satellite centered/zoomed to fit the parcel → the
 * estimator's 18×12 elevation lattice.
 *
 * Unlike fetch-real.mts (the 5-acre meadow set), the whole point here is
 * the county-recorded boundary itself — so the parcel ring lands in the
 * output, in canvas px, ready to draw.
 *
 * usage: AD_ADDR="..." npx tsx marketing/fence-ads/src/fetch-real2.mts
 * writes: src/plates/real2-aerial.png, real2-topo.js, real2-meta.json
 *         (parcel ring included in meta AND as real2-parcel.js)
 */
import { readFileSync, writeFileSync } from "fs";

// Vault-backed key resolution needs DATABASE_URL + APP_ENCRYPTION_KEY in
// process.env BEFORE lib/db loads — bootstrap from .env, then import.
const envFile = readFileSync(new URL("../../../.env", import.meta.url), "utf8");
for (const line of envFile.split("\n")) {
  const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
  if (m && !process.env[m[1]]) process.env[m[1]] = m[2].trim().replace(/^"|"$/g, "");
}

const geo = await import("@/lib/fence/geo");
const { CANVAS_W, CANVAS_H, MAP_W, MAP_H, MAP_SCALE, canvasPxPerFt, canvasToLatLng, latLngToCanvas, zoomToFit, centroid } = geo;
const { buildContours, pickContourInterval } = await import("@/lib/fence/contours");
const { resolveMarket } = await import("@/lib/fence/market");
const { reportallByPoint } = await import("@/lib/reportall");
const { getActiveApiKey } = await import("@/lib/api-keys");

const ADDRESS = process.env.AD_ADDR || "230 Avenue B, Snohomish, WA 98290";
// Vault first, env fallback — the same resolution order as the app;
// the .env copy can go stale after a dashboard key rotation.
const KEY = (await getActiveApiKey("GOOGLE_MAPS")) ?? process.env.GOOGLE_MAPS_API_KEY;
if (!KEY) throw new Error("no Google Maps key in vault or .env");
const DIR = new URL("./plates/", import.meta.url).pathname;

/* ---------- 1. geocode ---------- */
const gu = new URL("https://maps.googleapis.com/maps/api/geocode/json");
gu.searchParams.set("address", ADDRESS);
gu.searchParams.set("key", KEY);
const g = await (await fetch(gu)).json();
if (g.status !== "OK") throw new Error("geocode: " + g.status);
const loc = g.results[0].geometry.location as { lat: number; lng: number };
const formatted = g.results[0].formatted_address as string;
console.log("geocoded:", formatted, JSON.stringify(loc));

/* ---------- 2. the REAL parcel — same client the app uses ---------- */
const parcel = await reportallByPoint(loc);
if (!parcel || parcel.rings.length === 0) throw new Error("no parcel returned — try another address");
// The ring that actually contains/centers on the geocode point: largest.
const ring = [...parcel.rings].sort((a, b) => b.length - a.length)[0];
const center = centroid(ring);
const ZOOM = zoomToFit(ring, 19);
console.log(`parcel: ${ring.length} vertices · ${parcel.acres ?? "?"} ac · APN ${parcel.apn ?? "?"} · zoom ${ZOOM}`);

/* ---------- 3. satellite tile at the app's geometry ---------- */
const su = new URL("https://maps.googleapis.com/maps/api/staticmap");
su.searchParams.set("center", `${center.lat},${center.lng}`);
su.searchParams.set("zoom", String(ZOOM));
su.searchParams.set("size", `${MAP_W}x${MAP_H}`);
su.searchParams.set("scale", String(MAP_SCALE));
su.searchParams.set("maptype", "satellite");
su.searchParams.set("key", KEY);
const img = await fetch(su);
if (!img.ok) throw new Error("staticmap: " + img.status);
writeFileSync(`${DIR}real2-aerial.png`, Buffer.from(await img.arrayBuffer()));
console.log("aerial → real2-aerial.png");

/* ---------- 4. parcel ring in canvas px ---------- */
const rnd = (n: number) => Math.round(n * 10) / 10;
const ringPx = ring.map((p) => {
  const q = latLngToCanvas(p, center, ZOOM);
  return [rnd(q.x), rnd(q.y)] as [number, number];
});
writeFileSync(
  `${DIR}real2-parcel.js`,
  `/* generated by fetch-real2.mts — county parcel ring, canvas px */\nwindow.REAL2_PARCEL = ${JSON.stringify({ ring: ringPx, acres: parcel.acres, apn: parcel.apn })};\n`,
);
console.log(`parcel ring → real2-parcel.js (${ringPx.length} pts)`);

/* ---------- 5. elevation lattice (estimator's 18×12) ---------- */
const COLS = 18, ROWS = 12;
const pts: { lat: number; lng: number }[] = [];
for (let r = 0; r < ROWS; r++)
  for (let c = 0; c < COLS; c++)
    pts.push(canvasToLatLng({ x: (c * CANVAS_W) / (COLS - 1), y: (r * CANVAS_H) / (ROWS - 1) }, center, ZOOM));
const eu = new URL("https://maps.googleapis.com/maps/api/elevation/json");
eu.searchParams.set("locations", pts.map((p) => `${p.lat.toFixed(7)},${p.lng.toFixed(7)}`).join("|"));
eu.searchParams.set("key", KEY);
const ele = await (await fetch(eu)).json();
if (ele.status !== "OK") throw new Error("elevation: " + ele.status);
const M2FT = 3.28084;
const flat: number[] = ele.results.map((x: { elevation: number }) => x.elevation * M2FT);
const grid: number[][] = [];
for (let r = 0; r < ROWS; r++) grid.push(flat.slice(r * COLS, (r + 1) * COLS));
let min = Infinity, max = -Infinity;
for (const row of grid) for (const v of row) { min = Math.min(min, v); max = Math.max(max, v); }
const intervalFt = pickContourInterval(min, max);
const rel = grid.map((row) => row.map((v) => v - min));
const lines = buildContours(rel, CANVAS_W / (COLS - 1), CANVAS_H / (ROWS - 1), intervalFt);
const out = lines.map((l) => ({
  levelFt: rnd(l.levelFt),
  chains: l.chains.map((ch) => ch.map((p) => [rnd(p.x), rnd(p.y)])),
}));
writeFileSync(
  `${DIR}real2-topo.js`,
  `/* generated by fetch-real2.mts */\nwindow.REAL2_TOPO = ${JSON.stringify({ intervalFt, riseFt: rnd(max - min), lines: out })};\nwindow.REAL2_GRID = ${JSON.stringify(rel.map((row) => row.map(rnd)))};\n`,
);
console.log(`elevation: span ${(max - min).toFixed(1)} ft · interval ${intervalFt}′`);

/* ---------- 6. meta ---------- */
const market = resolveMarket({ address: formatted });
const meta = {
  address: formatted,
  center,
  zoom: ZOOM,
  pxPerFt: canvasPxPerFt(center.lat, ZOOM),
  acres: parcel.acres,
  apn: parcel.apn,
  market: { label: market.label, labor: market.labor },
};
writeFileSync(`${DIR}real2-meta.json`, JSON.stringify(meta, null, 2));
console.log("meta:", JSON.stringify(meta));
process.exit(0);
