/**
 * Generate the topo overlay for the slope ad using the APP'S OWN
 * marching-squares contour code, so the lines in the ad are the lines
 * the estimator would actually draw.
 *
 * Feeds buildContours an 18×12 elevation lattice (the same density the
 * estimator samples — fence-estimator.tsx TOPO_COLS/TOPO_ROWS) for a
 * yard that falls ~24 ft toward the south-west, then emits the chains,
 * the label placements and the interval as a plain JS global the ad
 * loads with a <script src>. (fetch() of JSON is blocked on file://.)
 *
 * usage: npx tsx marketing/fence-ads/src/render-topo.mts
 */
import { writeFileSync } from "fs";
import { buildContours, pickContourInterval } from "@/lib/fence/contours";

const COLS = 18;
const ROWS = 12;
const CANVAS_W = 900;
const CANVAS_H = 580;
const cellW = CANVAS_W / (COLS - 1);
const cellH = CANVAS_H / (ROWS - 1);

/** A hillside that falls toward the south-west, with a gentle bench
 *  across the middle so the contours aren't dead-parallel. Datum is the
 *  low point, matching the canvas legend ("feet above the low point"),
 *  so levels come out as clean multiples of the interval. */
const TOTAL_RISE_FT = 24;
const grid: number[][] = [];
for (let r = 0; r < ROWS; r++) {
  const row: number[] = [];
  for (let c = 0; c < COLS; c++) {
    const u = c / (COLS - 1); // 0 west → 1 east
    const v = r / (ROWS - 1); // 0 north → 1 south
    const fall = 0.62 * (1 - v) + 0.38 * u; // high in the NE, low in the SW
    const bench = 0.06 * Math.sin(v * Math.PI * 1.6) * Math.cos(u * Math.PI * 1.1);
    row.push((fall + bench) * TOTAL_RISE_FT);
  }
  grid.push(row);
}

let min = Infinity;
let max = -Infinity;
for (const row of grid) for (const v of row) { min = Math.min(min, v); max = Math.max(max, v); }
const intervalFt = pickContourInterval(min, max);
const lines = buildContours(grid, cellW, cellH, intervalFt);

const chainLen = (ch: { x: number; y: number }[]) => {
  let d = 0;
  for (let i = 1; i < ch.length; i++) d += Math.hypot(ch[i].x - ch[i - 1].x, ch[i].y - ch[i - 1].y);
  return d;
};

/* Label placement, matching fence-canvas: at most the 3 longest chains
   per level, nothing under 70px, nothing within 26px of an edge. */
const out = lines.map((l) => {
  const chains = l.chains.map((ch) => ch.map((p) => [round(p.x), round(p.y)]));
  const labels: [number, number][] = [];
  [...l.chains]
    .sort((a, b) => chainLen(b) - chainLen(a))
    .slice(0, 3)
    .forEach((ch) => {
      if (chainLen(ch) < 70) return;
      const m = ch[Math.floor(ch.length / 2)];
      if (m.x < 26 || m.x > CANVAS_W - 26 || m.y < 26 || m.y > CANVAS_H - 26) return;
      labels.push([round(m.x), round(m.y)]);
    });
  return { levelFt: round(l.levelFt), chains, labels };
});

function round(n: number) {
  return Math.round(n * 10) / 10;
}

const js =
  `/* generated by render-topo.mts — do not edit */\n` +
  `window.TOPO = ${JSON.stringify({ intervalFt, riseFt: round(max - min), lines: out })};\n`;
const dest = new URL("./plates/topo.js", import.meta.url).pathname;
writeFileSync(dest, js);
console.log(
  `interval ${intervalFt}′ · rise ${round(max - min)}′ · ${out.length} levels · ` +
    `${out.reduce((a, l) => a + l.chains.length, 0)} chains · ` +
    `${out.reduce((a, l) => a + l.labels.length, 0)} labels → ${dest}`,
);
